# Generated by Django 2.2.12 on 2020-04-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.TextField(default='no specific program'),
            preserve_default=False,
        ),
    ]
