# Generated by Django 2.2.12 on 2020-04-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Eays'), ('Doable', 'Doable'), ('Difficult', 'Difficult'), ('Very difficult', 'Very difficult')], default='Doable', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(choices=[('DJANGO', 'Django'), ('PYTHON', 'Python'), ('HTML', 'html'), ('SQL', 'sql'), ('CSS', 'css'), ('GIT', 'git'), ('OTHER', 'other')], default='DJANGO', max_length=10),
        ),
    ]
