# Generated by Django 2.2.12 on 2020-04-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200406_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='learned',
            field=models.BooleanField(default='False'),
        ),
    ]
