# Generated by Django 2.2.12 on 2020-04-07 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200407_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Question'),
        ),
    ]
