# Generated by Django 2.2.12 on 2020-04-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200421_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollschoices',
            old_name='poll',
            new_name='question_id',
        ),
    ]
