# Generated by Django 2.2.12 on 2020-05-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_visitorsinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorsinfo',
            name='skillsDjango',
            field=models.IntegerField(default=0),
        ),
    ]
